# Generated by Django 4.1.2 on 2022-10-29 13:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('subject', models.CharField(max_length=1500)),
                ('body', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='users.profile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='users.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
