# Generated by Django 4.1.2 on 2022-10-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, default='static/projects/today.png', null=True, upload_to='static/projects'),
        ),
    ]
