# Generated by Django 4.1.2 on 2022-10-30 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', 'vote_total', 'title']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created']},
        ),
    ]
